#!/usr/bin/env bash
#/bin/sh -c /bin/date
/usr/bin/php -S 0.0.0.0:80 -t /var/www/html/public/
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
#if [ ! -z "$WWWUSER" ]; then
#    usermod -u $WWWUSER mimotic
#fi
#
#if [ ! -d /.composer ]; then
#    mkdir /.composer
#fi
#
#chmod -R ugo+rw /.composer
#
#if [ $# -gt 0 ]; then
#    exec gosu $WWWUSER "$@"
#else
#    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
#fi
